# ==========================================================
# 您的Butterfly主题最终配置文件
# ==========================================================

# --- 首页配置 ---
# 首页封面图
index_img: /img/carousel.jpg

# 文章列表的样式 (card/masonry)
post_list:
  style: card

# --- 社交链接 ---
# 用于侧边栏和页脚
social:
  fab fa-github: https://github.com/zjncs || Github
  fas fa-envelope: mailto:zhaojianing@tju.edu.cn || Email

# --- 侧边栏配置 (问题的核心) ---
aside:
  # 总开关，必须为 true
  enable: true
  # 侧边栏在右侧
  position: right
  # 移动端显示侧边栏按钮
  mobile: true
  # 显示所有侧边栏内容（文章归档、标签、分类）
  display:
    archive: true
    tag: true
    category: true
  # 作者信息卡片
  card_author:
    enable: true
    avatar: /img/avatar.png
    author: Johnny-Zhao
    description: Attention is all you need.

# --- 自定义文件注入 ---
# 用于加载您自己的 CSS 或 JS
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">

# --- 图片放大预览功能 ---
# 开启后，点击文章中的图片可以放大
lightbox: fancybox